version: '3.9'

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_DATABASE=url_management
  localstack_main:
    image: localstack/localstack:latest
    network_mode: bridge
    ports:
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=dynamodb,sqs,sns
      - HOST_TMP_FOLDER=${PWD}/.docker/localstack
    volumes:
      - "./.docker/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
